### ISSUE TITLE
Adjustments (maybe) needed for engine PR 3456

### ISSUE THREAD

**Issue by Cervator** [Terasology/GooeyDefence#30]
Merging MovingBlocks/Terasology#3456 causes an error on auto save in this module, although *exactly* what causes it eludes me. First time I believe I hit it nearly immediately after having activated the shrine (`e` clicking it). Second time a fast enemy wave  I placed three towers on the paths and triggered the wave (regular enemies that time). On the auto-save following that the game crashed with the error below.

To place the towers open the inventory (with `i`) and buy a core + a single targeter + a plain damage effector. Place one set on each path then go activate the wave and watch the fireworks.

Sending this @eviltak's way as the author of the engine PR and/or to @jellysnake if interested :-)

Log snippet on crash (which locked the game entirely):

```
21:49:24.008 [main] INFO  o.t.p.i.ReadWriteStorageManager - Auto Saving - Creating game snapshot
21:49:24.008 [main] INFO  o.t.p.i.ReadWriteStorageManager - Auto Saving - Snapshot created: Writing phase starts
21:49:24.044 [Saving-0] ERROR o.t.p.internal.SaveTransaction - Save game creation failed
java.lang.NullPointerException: null
	at org.terasology.persistence.typeHandling.coreTypes.RuntimeDelegatingTypeHandler.serializeNonNull(RuntimeDelegatingTypeHandler.java:86)
	at org.terasology.persistence.typeHandling.TypeHandler.serialize(TypeHandler.java:49)
	at org.terasology.persistence.typeHandling.coreTypes.CollectionTypeHandler.serializeNonNull(CollectionTypeHandler.java:42)
	at org.terasology.persistence.typeHandling.coreTypes.CollectionTypeHandler.serializeNonNull(CollectionTypeHandler.java:28)
	at org.terasology.persistence.typeHandling.TypeHandler.serialize(TypeHandler.java:49)
	at org.terasology.persistence.typeHandling.coreTypes.RuntimeDelegatingTypeHandler.serializeNonNull(RuntimeDelegatingTypeHandler.java:86)
	at org.terasology.persistence.typeHandling.TypeHandler.serialize(TypeHandler.java:49)
	at org.terasology.persistence.typeHandling.coreTypes.ObjectFieldMapTypeHandler.serializeNonNull(ObjectFieldMapTypeHandler.java:69)
	at org.terasology.persistence.typeHandling.TypeHandler.serialize(TypeHandler.java:49)
	at org.terasology.persistence.typeHandling.coreTypes.RuntimeDelegatingTypeHandler.serializeNonNull(RuntimeDelegatingTypeHandler.java:98)
	at org.terasology.persistence.typeHandling.TypeHandler.serialize(TypeHandler.java:49)
	at org.terasology.persistence.typeHandling.coreTypes.ObjectFieldMapTypeHandler.serializeNonNull(ObjectFieldMapTypeHandler.java:69)
	at org.terasology.persistence.typeHandling.TypeHandler.serialize(TypeHandler.java:49)
	at org.terasology.persistence.typeHandling.coreTypes.RuntimeDelegatingTypeHandler.serializeNonNull(RuntimeDelegatingTypeHandler.java:86)
	at org.terasology.persistence.typeHandling.TypeHandler.serialize(TypeHandler.java:49)
	at org.terasology.persistence.typeHandling.coreTypes.ObjectFieldMapTypeHandler.serializeNonNull(ObjectFieldMapTypeHandler.java:69)
	at org.terasology.persistence.typeHandling.TypeHandler.serialize(TypeHandler.java:49)
	at org.terasology.persistence.typeHandling.coreTypes.RuntimeDelegatingTypeHandler.serializeNonNull(RuntimeDelegatingTypeHandler.java:86)
	at org.terasology.persistence.typeHandling.TypeHandler.serialize(TypeHandler.java:49)
	at org.terasology.persistence.typeHandling.coreTypes.ObjectFieldMapTypeHandler.serializeNonNull(ObjectFieldMapTypeHandler.java:69)
	at org.terasology.persistence.typeHandling.TypeHandler.serialize(TypeHandler.java:49)
	at org.terasology.persistence.typeHandling.Serializer.serialize(Serializer.java:64)
	at org.terasology.persistence.serializers.ComponentSerializer.serialize(ComponentSerializer.java:231)
	at org.terasology.persistence.serializers.EntitySerializer.serializeEntityDelta(EntitySerializer.java:335)
	at org.terasology.persistence.serializers.EntitySerializer.serialize(EntitySerializer.java:161)
	at org.terasology.persistence.internal.EntityStorer.store(EntityStorer.java:67)
	at org.terasology.persistence.internal.EntityStorer.store(EntityStorer.java:57)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at org.terasology.persistence.internal.CompressedChunkBuilder.<init>(CompressedChunkBuilder.java:52)
	at org.terasology.persistence.internal.SaveTransaction.prepareCompressedChunkBuilders(SaveTransaction.java:232)
	at org.terasology.persistence.internal.SaveTransaction.prepareChunksPlayersAndGlobalStore(SaveTransaction.java:211)
	at org.terasology.persistence.internal.SaveTransaction.run(SaveTransaction.java:149)
	at org.terasology.utilities.concurrency.TaskProcessor.run(TaskProcessor.java:50)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
21:49:24.067 [main] ERROR o.terasology.engine.TerasologyEngine - Uncaught exception, attempting clean game shutdown
java.lang.RuntimeException: Saving failed
	at org.terasology.persistence.internal.ReadWriteStorageManager.checkSaveTransactionAndClearUpIfItIsDone(ReadWriteStorageManager.java:177)
	at org.terasology.persistence.internal.ReadWriteStorageManager.update(ReadWriteStorageManager.java:405)
	at org.terasology.engine.modes.StateIngame.update(StateIngame.java:179)
	at org.terasology.engine.TerasologyEngine.tick(TerasologyEngine.java:458)
	at org.terasology.engine.TerasologyEngine.mainLoop(TerasologyEngine.java:421)
	at org.terasology.engine.TerasologyEngine.run(TerasologyEngine.java:397)
	at org.terasology.engine.Terasology.main(Terasology.java:154)
Caused by: java.lang.NullPointerException: null
	at org.terasology.persistence.typeHandling.coreTypes.RuntimeDelegatingTypeHandler.serializeNonNull(RuntimeDelegatingTypeHandler.java:86)
	at org.terasology.persistence.typeHandling.TypeHandler.serialize(TypeHandler.java:49)
	at org.terasology.persistence.typeHandling.coreTypes.CollectionTypeHandler.serializeNonNull(CollectionTypeHandler.java:42)
	at org.terasology.persistence.typeHandling.coreTypes.CollectionTypeHandler.serializeNonNull(CollectionTypeHandler.java:28)
	at org.terasology.persistence.typeHandling.TypeHandler.serialize(TypeHandler.java:49)
	at org.terasology.persistence.typeHandling.coreTypes.RuntimeDelegatingTypeHandler.serializeNonNull(RuntimeDelegatingTypeHandler.java:86)
	at org.terasology.persistence.typeHandling.TypeHandler.serialize(TypeHandler.java:49)
	at org.terasology.persistence.typeHandling.coreTypes.ObjectFieldMapTypeHandler.serializeNonNull(ObjectFieldMapTypeHandler.java:69)
	at org.terasology.persistence.typeHandling.TypeHandler.serialize(TypeHandler.java:49)
	at org.terasology.persistence.typeHandling.coreTypes.RuntimeDelegatingTypeHandler.serializeNonNull(RuntimeDelegatingTypeHandler.java:98)
	at org.terasology.persistence.typeHandling.TypeHandler.serialize(TypeHandler.java:49)
	at org.terasology.persistence.typeHandling.coreTypes.ObjectFieldMapTypeHandler.serializeNonNull(ObjectFieldMapTypeHandler.java:69)
	at org.terasology.persistence.typeHandling.TypeHandler.serialize(TypeHandler.java:49)
	at org.terasology.persistence.typeHandling.coreTypes.RuntimeDelegatingTypeHandler.serializeNonNull(RuntimeDelegatingTypeHandler.java:86)
	at org.terasology.persistence.typeHandling.TypeHandler.serialize(TypeHandler.java:49)
	at org.terasology.persistence.typeHandling.coreTypes.ObjectFieldMapTypeHandler.serializeNonNull(ObjectFieldMapTypeHandler.java:69)
	at org.terasology.persistence.typeHandling.TypeHandler.serialize(TypeHandler.java:49)
	at org.terasology.persistence.typeHandling.coreTypes.RuntimeDelegatingTypeHandler.serializeNonNull(RuntimeDelegatingTypeHandler.java:86)
	at org.terasology.persistence.typeHandling.TypeHandler.serialize(TypeHandler.java:49)
	at org.terasology.persistence.typeHandling.coreTypes.ObjectFieldMapTypeHandler.serializeNonNull(ObjectFieldMapTypeHandler.java:69)
	at org.terasology.persistence.typeHandling.TypeHandler.serialize(TypeHandler.java:49)
	at org.terasology.persistence.typeHandling.Serializer.serialize(Serializer.java:64)
	at org.terasology.persistence.serializers.ComponentSerializer.serialize(ComponentSerializer.java:231)
	at org.terasology.persistence.serializers.EntitySerializer.serializeEntityDelta(EntitySerializer.java:335)
	at org.terasology.persistence.serializers.EntitySerializer.serialize(EntitySerializer.java:161)
	at org.terasology.persistence.internal.EntityStorer.store(EntityStorer.java:67)
	at org.terasology.persistence.internal.EntityStorer.store(EntityStorer.java:57)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at org.terasology.persistence.internal.CompressedChunkBuilder.<init>(CompressedChunkBuilder.java:52)
	at org.terasology.persistence.internal.SaveTransaction.prepareCompressedChunkBuilders(SaveTransaction.java:232)
	at org.terasology.persistence.internal.SaveTransaction.prepareChunksPlayersAndGlobalStore(SaveTransaction.java:211)
	at org.terasology.persistence.internal.SaveTransaction.run(SaveTransaction.java:149)
	at org.terasology.utilities.concurrency.TaskProcessor.run(TaskProcessor.java:50)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
21:49:24.071 [main] INFO  o.terasology.engine.TerasologyEngine - Shutting down Terasology...
21:49:24.539 [main] ERROR o.terasology.engine.TerasologyEngine - Clean game shutdown after an uncaught exception failed
java.lang.NullPointerException: null
	at org.terasology.persistence.typeHandling.coreTypes.RuntimeDelegatingTypeHandler.serializeNonNull(RuntimeDelegatingTypeHandler.java:86)
	at org.terasology.persistence.typeHandling.TypeHandler.serialize(TypeHandler.java:49)
	at org.terasology.persistence.typeHandling.coreTypes.CollectionTypeHandler.serializeNonNull(CollectionTypeHandler.java:42)
	at org.terasology.persistence.typeHandling.coreTypes.CollectionTypeHandler.serializeNonNull(CollectionTypeHandler.java:28)
	at org.terasology.persistence.typeHandling.TypeHandler.serialize(TypeHandler.java:49)
	at org.terasology.persistence.typeHandling.coreTypes.RuntimeDelegatingTypeHandler.serializeNonNull(RuntimeDelegatingTypeHandler.java:86)
	at org.terasology.persistence.typeHandling.TypeHandler.serialize(TypeHandler.java:49)
	at org.terasology.persistence.typeHandling.coreTypes.ObjectFieldMapTypeHandler.serializeNonNull(ObjectFieldMapTypeHandler.java:69)
	at org.terasology.persistence.typeHandling.TypeHandler.serialize(TypeHandler.java:49)
	at org.terasology.persistence.typeHandling.coreTypes.RuntimeDelegatingTypeHandler.serializeNonNull(RuntimeDelegatingTypeHandler.java:98)
	at org.terasology.persistence.typeHandling.TypeHandler.serialize(TypeHandler.java:49)
	at org.terasology.persistence.typeHandling.coreTypes.ObjectFieldMapTypeHandler.serializeNonNull(ObjectFieldMapTypeHandler.java:69)
	at org.terasology.persistence.typeHandling.TypeHandler.serialize(TypeHandler.java:49)
	at org.terasology.persistence.typeHandling.coreTypes.RuntimeDelegatingTypeHandler.serializeNonNull(RuntimeDelegatingTypeHandler.java:86)
	at org.terasology.persistence.typeHandling.TypeHandler.serialize(TypeHandler.java:49)
	at org.terasology.persistence.typeHandling.coreTypes.ObjectFieldMapTypeHandler.serializeNonNull(ObjectFieldMapTypeHandler.java:69)
	at org.terasology.persistence.typeHandling.TypeHandler.serialize(TypeHandler.java:49)
	at org.terasology.persistence.typeHandling.coreTypes.RuntimeDelegatingTypeHandler.serializeNonNull(RuntimeDelegatingTypeHandler.java:86)
	at org.terasology.persistence.typeHandling.TypeHandler.serialize(TypeHandler.java:49)
	at org.terasology.persistence.typeHandling.coreTypes.ObjectFieldMapTypeHandler.serializeNonNull(ObjectFieldMapTypeHandler.java:69)
	at org.terasology.persistence.typeHandling.TypeHandler.serialize(TypeHandler.java:49)
	at org.terasology.persistence.typeHandling.Serializer.serialize(Serializer.java:64)
	at org.terasology.persistence.serializers.ComponentSerializer.serialize(ComponentSerializer.java:231)
	at org.terasology.persistence.serializers.EntitySerializer.serializeEntityDelta(EntitySerializer.java:335)
	at org.terasology.persistence.serializers.EntitySerializer.serialize(EntitySerializer.java:161)
	at org.terasology.persistence.internal.EntityStorer.store(EntityStorer.java:67)
	at org.terasology.persistence.internal.EntityStorer.store(EntityStorer.java:57)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at org.terasology.persistence.internal.CompressedChunkBuilder.<init>(CompressedChunkBuilder.java:52)
	at org.terasology.persistence.internal.ReadWriteStorageManager.deactivateChunk(ReadWriteStorageManager.java:332)
	at org.terasology.world.chunks.localChunkProvider.LocalChunkProvider.unloadChunkInternal(LocalChunkProvider.java:446)
	at org.terasology.world.chunks.localChunkProvider.LocalChunkProvider.dispose(LocalChunkProvider.java:575)
	at org.terasology.engine.modes.StateIngame.dispose(StateIngame.java:117)
	at org.terasology.engine.TerasologyEngine.cleanup(TerasologyEngine.java:482)
	at org.terasology.engine.TerasologyEngine.run(TerasologyEngine.java:403)
	at org.terasology.engine.Terasology.main(Terasology.java:154)
java.lang.RuntimeException: Saving failed
	at org.terasology.persistence.internal.ReadWriteStorageManager.checkSaveTransactionAndClearUpIfItIsDone(ReadWriteStorageManager.java:177)
	at org.terasology.persistence.internal.ReadWriteStorageManager.update(ReadWriteStorageManager.java:405)
	at org.terasology.engine.modes.StateIngame.update(StateIngame.java:179)
	at org.terasology.engine.TerasologyEngine.tick(TerasologyEngine.java:458)
	at org.terasology.engine.TerasologyEngine.mainLoop(TerasologyEngine.java:421)
	at org.terasology.engine.TerasologyEngine.run(TerasologyEngine.java:397)
	at org.terasology.engine.Terasology.main(Terasology.java:154)
Caused by: java.lang.NullPointerException
	at org.terasology.persistence.typeHandling.coreTypes.RuntimeDelegatingTypeHandler.serializeNonNull(RuntimeDelegatingTypeHandler.java:86)
	at org.terasology.persistence.typeHandling.TypeHandler.serialize(TypeHandler.java:49)
	at org.terasology.persistence.typeHandling.coreTypes.CollectionTypeHandler.serializeNonNull(CollectionTypeHandler.java:42)
	at org.terasology.persistence.typeHandling.coreTypes.CollectionTypeHandler.serializeNonNull(CollectionTypeHandler.java:28)
	at org.terasology.persistence.typeHandling.TypeHandler.serialize(TypeHandler.java:49)
	at org.terasology.persistence.typeHandling.coreTypes.RuntimeDelegatingTypeHandler.serializeNonNull(RuntimeDelegatingTypeHandler.java:86)
	at org.terasology.persistence.typeHandling.TypeHandler.serialize(TypeHandler.java:49)
	at org.terasology.persistence.typeHandling.coreTypes.ObjectFieldMapTypeHandler.serializeNonNull(ObjectFieldMapTypeHandler.java:69)
	at org.terasology.persistence.typeHandling.TypeHandler.serialize(TypeHandler.java:49)
	at org.terasology.persistence.typeHandling.coreTypes.RuntimeDelegatingTypeHandler.serializeNonNull(RuntimeDelegatingTypeHandler.java:98)
	at org.terasology.persistence.typeHandling.TypeHandler.serialize(TypeHandler.java:49)
	at org.terasology.persistence.typeHandling.coreTypes.ObjectFieldMapTypeHandler.serializeNonNull(ObjectFieldMapTypeHandler.java:69)
	at org.terasology.persistence.typeHandling.TypeHandler.serialize(TypeHandler.java:49)
	at org.terasology.persistence.typeHandling.coreTypes.RuntimeDelegatingTypeHandler.serializeNonNull(RuntimeDelegatingTypeHandler.java:86)
	at org.terasology.persistence.typeHandling.TypeHandler.serialize(TypeHandler.java:49)
	at org.terasology.persistence.typeHandling.coreTypes.ObjectFieldMapTypeHandler.serializeNonNull(ObjectFieldMapTypeHandler.java:69)
	at org.terasology.persistence.typeHandling.TypeHandler.serialize(TypeHandler.java:49)
	at org.terasology.persistence.typeHandling.coreTypes.RuntimeDelegatingTypeHandler.serializeNonNull(RuntimeDelegatingTypeHandler.java:86)
	at org.terasology.persistence.typeHandling.TypeHandler.serialize(TypeHandler.java:49)
	at org.terasology.persistence.typeHandling.coreTypes.ObjectFieldMapTypeHandler.serializeNonNull(ObjectFieldMapTypeHandler.java:69)
	at org.terasology.persistence.typeHandling.TypeHandler.serialize(TypeHandler.java:49)
	at org.terasology.persistence.typeHandling.Serializer.serialize(Serializer.java:64)
	at org.terasology.persistence.serializers.ComponentSerializer.serialize(ComponentSerializer.java:231)
	at org.terasology.persistence.serializers.EntitySerializer.serializeEntityDelta(EntitySerializer.java:335)
	at org.terasology.persistence.serializers.EntitySerializer.serialize(EntitySerializer.java:161)
	at org.terasology.persistence.internal.EntityStorer.store(EntityStorer.java:67)
	at org.terasology.persistence.internal.EntityStorer.store(EntityStorer.java:57)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at org.terasology.persistence.internal.CompressedChunkBuilder.<init>(CompressedChunkBuilder.java:52)
	at org.terasology.persistence.internal.SaveTransaction.prepareCompressedChunkBuilders(SaveTransaction.java:232)
	at org.terasology.persistence.internal.SaveTransaction.prepareChunksPlayersAndGlobalStore(SaveTransaction.java:211)
	at org.terasology.persistence.internal.SaveTransaction.run(SaveTransaction.java:149)
	at org.terasology.utilities.concurrency.TaskProcessor.run(TaskProcessor.java:50)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
For more details, see the log files in C:\Dev\Terasology\Git\ModuleMegaWorkspace\Terasology\logs\2018-09-04_21-45-42
```

**Comment by Cervator** [comment]
Note: This is now tied to https://github.com/MovingBlocks/Terasology/issues/3490 instead - see it for details

**Comment by eviltak** [comment]
@Cervator I just pushed a commit to MovingBlocks/Terasology#3535 which seems to have fixed the problem for me. Can you test and confirm please?

**Comment by skaldarnar** [comment]
@Cervator did you test this by any chance? Is this still required? Not promising anything, but maybe @jdrueckert or me can see whether GooeyDefence works without this fix with the serialization overhaul...

**Comment by jdrueckert** [comment]
@skaldarnar Don't recall: did we try this out? :thinking:

**Comment by Cervator** [comment]
No idea, but it sounds like there's a newer typehandling issue now, have noted it myself for the last couple play tests. Seems to trigger after you've got one or two waves going.
